export enum PrismaErrors {
    AuthenticationFailed = "P1000",
    DatabaseServerNotFound = "P1001",
    DatabaseServerWasReachedButTimedOut = "P1002",
    DatabaseNameDoesNotExist = "P1003",
    DatabaseServerTimeOut = "P1008",
    DatabaseNameAlreadyExists = "P1009",
    UserWasDeniedAccess = "P1010",
    OpeningTLSConnection = "P1011",
    SchemaInvalid = "P1012",
    DatabaseStringInvalid = "P1013",
    UnderlyingKindForModelDoesNotExist = "P1014",
    SchemaUsingFeaturesNotSupported = "P1015",
    IncorrectNumberOfParametersInRawQuery = "P1016",
    ServerConnectionClosed = "P1017",
    ValueForTheColumnIsTooLong = "P2000",
    WhereConditionDoesNotExist = "P2001",
    UniqueCoinstraintFail = "P2002",
    ForeingKeyConstraintFailed = "P2003",
    ConstraintFailedOnTheDatabase = "P2004",
    InvalidFieldNameForFieldType = "P2005",
}